dataset:
  paths:
    - "data/raw/motor_data11-14lats.csv"
    - "data/raw/motor_data14-2018.csv"

stream:
  batch_size: 50000
  delay_seconds: 0.5

storage:
  path: "database.db"
  raw_table: "raw_batches"
  cleaned_table: "cleaned_batches"
  metadata_table: "metadata"

logging:
  level: "INFO"
  path: "collection.log"