name: Цикл обучения модели

on: [ push, pull_request ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Запуск полного цикла обучения
        run: python run.py -mode "update"